### ISSUE TITLE
Default split manager

### ISSUE THREAD

**Issue by tfrsw** [KevinMusgrave/powerful-benchmarker#109]
Thank you for creating a fairly helpful library! 
I am currently working on a new metric learning loss function and benchmarking it using your library.
I have already run a couple of bayesian optimization experiments (for CosFace, ArcFace, mine, etc.) without using the` --split_manager~SWAP~1 {MLRCSplitManager: {}} ` flag.
Does this cause an unfair comparison problem, such as different splitting results for different loss functions?

**Comment by KevinMusgrave** [comment]
If you're comparing with the numbers I obtained, then yes it's "unfair" because different splits could be easier or harder than the split I used. 

If you're comparing with your own numbers, then it's fine to use your own splits.

On a related note you may find [this paper and its code](https://github.com/Confusezius/Characterizing_Generalization_in_DeepMetricLearning) interesting. They create splits with varying degrees of difficulty.

**Comment by KevinMusgrave** [comment]
One thing I should warn you about is that due to time-constraints, I can't provide technical support (bug fixes etc.) for the metric-learning branch of this repo.

**Comment by tfrsw** [comment]
Thank you for your reply!

> If you're comparing with your own numbers, then it's fine to use your own splits.

So does the default split manager always give us the same train/val/test splitting?

> One thing I should warn you about is that due to time-constraints, I can't provide technical support (bug fixes etc.) for the metric-learning branch of this repo.

I see your situation, but I think this must be the best benchmarking library for DML loss functions!

**Comment by KevinMusgrave** [comment]
> So does the default split manager always give us the same train/val/test splitting?

Yes
 
> I see your situation, but I think this must be the best benchmarking library for DML loss functions!

Thanks :smile:
