### ISSUE TITLE
Inference func/script

### ISSUE THREAD

**Issue by shaikaz** [KevinMusgrave/powerful-benchmarker#11]
Hi, 
Does anyone as  implemented an inference func/script? 
Given output of an experiment, (config files, weights file), and 2 images a function that will return the distance between the images according to the model's configuration.
I implemented my own, but I believe I made a mistake that I can't find out.
Thanks,
Shai

**Comment by KevinMusgrave** [comment]
@shaikaz Should the functionality be: given an experiment folder, load the best model weights, and perform inference on pairs of images. For each pair, output the distance. Save the results to a csv or sqlite file.

I guess this is similar to the existing tests, but it will give distances for specified pairs, rather than a single accuracy number.

Do I understand correctly?

**Comment by shaikaz** [comment]
@KevinMusgrave Yes, I wanted just the distance between any pair of random images. Thanks!

**Comment by KevinMusgrave** [comment]
@shaikaz I got around to making some simple inference code in pytorch-metric-learning. Not sure if it does exactly what you're thinking, but you can check it out in this notebook: https://colab.research.google.com/github/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/Inference.ipynb

**Comment by shaikaz** [comment]
I saw it, it's what I was thinking about. Thanks!

**Comment by KevinMusgrave** [comment]
Great! I'll close this issue. If you find bugs or have questions regarding utils.inference, please open an issue in pytorch-metric-learning.
