### ISSUE TITLE
Custom trainer

### ISSUE THREAD

**Issue by KhrulkovV** [KevinMusgrave/powerful-benchmarker#13]
Hello!

I was trying to run the training with a custom trainer (inherited from `trainers.MetricLossOnly`), which I registered as 
```
r = runner(**(args.__dict__))
r.register("trainer", MyTrainer)
r.run()
```
and correspondingly adjusted the config file
`training_method: MyTrainer`

However, the `run.py` scripts produces the following error:
```
AttributeError: module 'powerful_benchmarker.api_parsers' has no attribute 'APIMyTrainer'
```

What is the correct way to run a custom trainer? Basically, what I am trying to do is to modify positive pairs from a batch in a certain way (apply augmentations like in `UnsupervisedEmbeddingsUsingAugmentations`, but in a different way), maybe you can give some suggestions how it could be implemented in a different way?

Thanks in advance!

**Comment by KevinMusgrave** [comment]
@KhrulkovV Thanks for pointing this out! I think I should be able to fix this pretty quickly. I'll get back to you soon. (By the way I transferred this issue to the powerful-benchmarker repo.)

**Comment by KhrulkovV** [comment]
Amazing, thanks!

**Comment by KevinMusgrave** [comment]
Ok, I added API registration to the latest version, and also discovered a bug in easy-module-attribute-getter:
```
pip install powerful-benchmarker==0.9.18 easy-module-attribute-getter==0.9.33
```
When you create your own trainer, you need to also create an associated API parser. The name of the api parser should be ```APIParser<name of your training method>```. 

Here's an example where I make a trainer that takes in an additional argument ```foo```. In order to pass this in, the API parser needs to add ```foo``` to the trainer kwargs, and this is done in the ```get_trainer_kwargs``` method.

```python
from pytorch_metric_learning import trainers
from powerful_benchmarker import api_parsers

class YourTrainer(trainers.MetricLossOnly):
	def __init__(self, foo, **kwargs):
		super().__init__(**kwargs)
		self.foo = foo
		print("foo = ", self.foo)


class APIYourTrainer(api_parsers.BaseAPIParser):
    def get_foo(self):
        return "hello"

    def get_trainer_kwargs(self):
        trainer_kwargs = super().get_trainer_kwargs()
        trainer_kwargs["foo"] = self.get_foo()
        return trainer_kwargs

r = runner(**(args.__dict__))
r.register("trainer", YourTrainer)
r.register("api_parser", APIYourTrainer)
r.run()
```

If your trainer's ```__init__``` arguments are identical to the one you're extending, then you can just set ```APIYourTrainer = api_parsers.BaseAPIParser```. (Note that ```BaseAPIParser``` is the same as ```APIMetricLossOnly```.)

Let me know if that works.

**Comment by KhrulkovV** [comment]
Works now, thank you very much!
