### ISSUE TITLE
How to use the Bayesian optimization to tune ArcFaceLoss hyperparameters? 

### ISSUE THREAD

**Issue by CaiSudao** [KevinMusgrave/powerful-benchmarker#37]
I ran the code below. And returned the TypeEorror. I don't know how to add the embedding_size argument correctly.
python run.py --bayes_opt_iters 20
--loss_funcsOVERRIDE {metric_loss: {ArcFaceLoss: {embedding_size: 128, lrBAYESIAN: [0, 1], marginBAYESIAN: [0, 100], scaleBAYESIAN: [0, 100]}}}
--experiment_name bayes_opt20_ArcFaceLoss \

TypeError: init() missing 1 required positional argument: 'embedding_size'

**Comment by KevinMusgrave** [comment]
That's a confusing error message. Try this:
```
python run.py --bayes_opt_iters 20 \
--loss_funcs~OVERRIDE~ {metric_loss: {ArcFaceLoss: {embedding_size: 128, margin~BAYESIAN~: [0, 100], scale~BAYESIAN~: [0, 100]}}} \
--optimizers {metric_loss_optimizer: {RMSprop: {lr~LOG_BAYESIAN~: [0.000001, 0.1], momentum: 0.9, weight_decay: 0.0001}}} \
--experiment_name bayes_opt20_ArcFaceLoss
```
The optimizer for the loss function is specified separately. Also, ArcFaceLoss actually requires ```num_classes```, but the benchmarker figures this out, which is why we don't have to specify it here.

And here's another way you can run the above command
```
python run.py --bayes_opt_iters 20 \
--loss_funcs~OVERRIDE~ {metric_loss: {ArcFaceLoss: {embedding_size: 128, margin~BAYESIAN~: [0, 100], scale~BAYESIAN~: [0, 100]}}} \
--config_optimizers [default, with_metric_loss_optimizer_bayes_opt] \
--experiment_name bayes_opt20_ArcFaceLoss
```
This loads the default optimizer config file, followed by the ```with_metric_loss_optimizer_bayes_opt``` file. You can view both files [here](https://github.com/KevinMusgrave/powerful-benchmarker/tree/master/src/powerful_benchmarker/configs/config_optimizers).

**Comment by KevinMusgrave** [comment]
Closing for now, please reopen if you have more questions.
